"""added role_permissions table

Revision ID: 42b8cc2a24bb
Revises: 4abc01a0d8d3
Create Date: 2023-01-01 21:36:34.294922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import INTEGER, VARCHAR, NVARCHAR, Column, TIMESTAMP, func, ForeignKeyConstraint
import sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42b8cc2a24bb'
down_revision = '4abc01a0d8d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'role_permissions',
        Column('id', INTEGER, primary_key=True),
        Column("role_id", sa.Integer, sa.ForeignKey("roles.id"), nullable=False),
        Column("permission_id", sa.Integer, sa.ForeignKey("permissions.id"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
