"""added permissions table

Revision ID: 4abc01a0d8d3
Revises: 5211ab329fc4
Create Date: 2023-01-01 21:34:29.235853

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy import INTEGER, VARCHAR, NVARCHAR, Column, TIMESTAMP, func

# revision identifiers, used by Alembic.
revision = '4abc01a0d8d3'
down_revision = '5211ab329fc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table(
        'permissions',
        Column('id', INTEGER, primary_key=True),
        Column('name', VARCHAR(50), nullable=False),
        Column('created_at', TIMESTAMP, server_default=func.now()),
        Column('updated_at', TIMESTAMP, server_default=func.now(),onupdate=func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
