"""added roles table

Revision ID: 5211ab329fc4
Revises: 343c81ea7106
Create Date: 2023-01-01 21:31:13.102712

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy import INTEGER, VARCHAR, NVARCHAR, Column, TIMESTAMP, func

# revision identifiers, used by Alembic.
revision = '5211ab329fc4'
down_revision = '343c81ea7106'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        Column('id', INTEGER, primary_key=True),
        Column('name', VARCHAR(50), nullable=False),
        Column('created_at', TIMESTAMP, server_default=func.now()),
        Column('updated_at', TIMESTAMP, server_default=func.now(),onupdate=func.now())
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
