"""added user_roles table

Revision ID: a896ef3daeb3
Revises: 42b8cc2a24bb
Create Date: 2023-01-02 01:29:32.424848

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy
from sqlalchemy import INTEGER, VARCHAR, NVARCHAR, Column, TIMESTAMP, func
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a896ef3daeb3'
down_revision = '42b8cc2a24bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_roles',
        Column('id', INTEGER, primary_key=True),
        Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        Column("role_id", sa.Integer, sa.ForeignKey("roles.id"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
